name: Build and Deploy to Lambda

on:
  repository_dispatch:
    types: [test-completed]

jobs:
  setup-build-deploy:
    name: Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SBT
        uses: olafurpg/setup-scala@v10
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - name: Build into js
        run: sbt -v +fullLinkJS

#      - name: default deploy
#        uses: appleboy/lambda-action@master
#        with:
#          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws_region: ${{ secrets.AWS_REGION }}
#          memory_size: 128
#          timeout: 10
#          function_name: gorush
#          source: example/index.js

