name: Run tests

on:
  push:
    branches:
      - master

jobs:
  test-job:
    name: Test, Test, Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - name: SBT
        uses: olafurpg/setup-scala@v10
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - name: Build and Test
        run: sbt test