name: Run tests

on:
  push:
    branches:
      - master

jobs:
  test-job:
    name: Test, Test, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup SBT
        uses: olafurpg/setup-scala@v10
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - name: Run the test
        run: sbt -v +test

  trigger-release:
      name: Trigger Release
      runs-on: ubuntu-latest
      needs: test-job
      if: github.ref == 'refs/heads/master'

      steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v1
          with:
            event-type: test-completed