name: Run tests

on:
  push:
    branches:
      - master

jobs:
  test-job:
    name: Test, Test, Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Node
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm test
      - name: SBT action test
        id: sbt
        uses: lokkju/github-action-sbt@master
        with:
          commands: test