name: Run tests

on:
  push:
    branches:
      - master

jobs:
  test-job:
    name: Test, Test, Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: bahmutov/npm-install@v1
        with:
          working-directory: $(pwd)/target/scala-2.13/scalajs-bundler/test
      - name: SBT action test
        id: sbt
        uses: lokkju/github-action-sbt@master
        with:
          commands: test